using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.Serialization;

// ReSharper disable CheckNamespace

namespace GameLovers.UiService
{
	/// <summary>
	/// Represents a configuration of an <seealso cref="UiPresenter"/> with all it's important data
	/// The Id is the int representation of the UI generated by the UiIdsGenerator code generator
	/// </summary>
	public struct UiConfig
	{
		/// <summary>Gets the loader address used to instantiate this presenter.</summary>
		[FormerlySerializedAs("AddressableAddress")]
		public string Address;
		/// <summary>Gets the order applied to the presenter's resolved surface.</summary>
		public int Layer;
		/// <summary>Gets the presenter type represented by this configuration.</summary>
		public Type UiType;
		/// <summary>Gets whether supported loaders should instantiate this presenter synchronously.</summary>
		public bool LoadSynchronously;
		/// <summary>Gets the expected render space of the presenter.</summary>
		public UiSurfaceSpace Space;
		/// <summary>Gets the hierarchy placement used when the presenter is instantiated.</summary>
		public UiPlacementSpace Placement;
	}

	/// <summary>
	/// ScriptableObject tool to import the <seealso cref="UiConfig"/> & <seealso cref="UiSetConfig"/> to be used in the <see cref="IUiService"/>.
	/// Use one of the derived types to create a UiConfigs asset:
	/// <list type="bullet">
	/// <item><see cref="AddressablesUiConfigs"/> - for Addressables-based loading</item>
	/// <item><see cref="ResourcesUiConfigs"/> - for Resources folder loading</item>
	/// <item><see cref="PrefabRegistryUiConfigs"/> - for direct prefab references</item>
	/// </list>
	/// </summary>
	public abstract class UiConfigs : ScriptableObject//, IConfigsContainer<UiConfig>
	{
		[SerializeField]
		private List<UiConfigSerializable> _configs = new List<UiConfigSerializable>();
		[SerializeField]
		private List<UiSetConfigSerializable> _sets = new List<UiSetConfigSerializable>();

		/// <summary>
		/// Gets or sets the list of UI configurations
		/// </summary>
		public List<UiConfig> Configs
		{
			get { return _configs.ConvertAll(element => (UiConfig)element); }
			set { _configs = value.ConvertAll(element => (UiConfigSerializable)element); }
		}

		/// <summary>
		/// Gets the list of UI set configurations
		/// </summary>
		public List<UiSetConfig> Sets => _sets.ConvertAll(element => UiSetConfigSerializable.ToUiSetConfig(element));

		/// <summary>Replaces every serialized UI set; the editor's sync path owns this.</summary>
		internal void SetSets(IEnumerable<UiSetConfig> sets)
		{
			_sets.Clear();
			foreach (var set in sets)
			{
				_sets.Add(UiSetConfigSerializable.FromUiSetConfig(set));
			}
		}

		/// <summary>
		/// Sets the new size of this scriptable object <seealso cref="UiSetConfig"/> list.
		/// The UiConfigSets have the same id value that the index in the list.
		/// Validates entries against available UI configs.
		/// </summary>
		/// <param name="size">The new size of the list</param>
		public void SetSetsSize(int size)
		{
			var validTypeNames = new HashSet<string>(_configs.Select(c => c.UiType));
			
			if (size < _sets.Count)
			{
				_sets.RemoveRange(size, _sets.Count - size);
			}

			for (int i = 0; i < size; i++)
			{
				if (i < _sets.Count)
				{
					var set = _sets[i];
					
					// Initialize UiEntries if null
					if (set.UiEntries == null)
					{
						set.UiEntries = new List<UiSetEntry>();
					}
					
					// Remove entries that reference non-existent UI types
					set.UiEntries.RemoveAll(entry => !validTypeNames.Contains(entry.UiTypeName));
					_sets[i] = set;
					continue;
				}

				_sets.Add(new UiSetConfigSerializable { SetId = i, UiEntries = new List<UiSetEntry>() });
			}
		}

		/// <summary>
		/// Necessary to serialize the data in scriptable object
		/// </summary>
		[Serializable]
		public struct UiConfigSerializable
		{
			/// <summary>Gets the serialized loader address.</summary>
			[FormerlySerializedAs("AddressableAddress")]
			public string Address;
			/// <summary>Gets the serialized surface order.</summary>
			public int Layer;
			/// <summary>Gets the assembly-qualified presenter type name.</summary>
			public string UiType;
			/// <summary>Gets whether supported loaders should instantiate this presenter synchronously.</summary>
			public bool LoadSynchronously;
			/// <summary>Gets the serialized expected render space.</summary>
			public UiSurfaceSpace Space;
			/// <summary>Gets the serialized hierarchy placement.</summary>
			public UiPlacementSpace Placement;

			/// <summary>
			/// Rehydrates the runtime config, resolving <see cref="UiConfig.UiType"/> from the stored
			/// assembly-qualified name. Yields a null <c>UiType</c> when that type no longer exists.
			/// </summary>
			public static implicit operator UiConfig(UiConfigSerializable serializable)
			{
				return new UiConfig
				{
					Address = serializable.Address,
					Layer = serializable.Layer,
					UiType = Type.GetType(serializable.UiType),
					LoadSynchronously = serializable.LoadSynchronously,
					Space = serializable.Space,
					Placement = serializable.Placement
				};
			}

			/// <summary>
			/// Flattens the runtime config for YAML serialization, storing the presenter type by
			/// assembly-qualified name.
			/// </summary>
			public static implicit operator UiConfigSerializable(UiConfig config)
			{
				return new UiConfigSerializable
				{
					Address = config.Address,
					Layer = config.Layer,
					UiType = config.UiType.AssemblyQualifiedName,
					LoadSynchronously = config.LoadSynchronously,
					Space = config.Space,
					Placement = config.Placement
				};
			}
		}

	}
}